<?php

use Illuminate\Database\Seeder;
use App\Model\Classe;

class ClassesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $data = [

            [
        		'classes_name' => 'Webforce3',
        		'contact' => 'Lilian Delaportua',
        		'mail' => 'webforce@formation.com',
        		'tel' => '0523659586',
        		'city' => 'Bordeaux',
        		'cp' => '33000',
        		'address' => '13 rue abbé de l\'épée',
        		'cost' => '3200',
                'duration' => '3',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ABC CONSEIL SAMUEL BERNARDI',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'NICE',
                'cp' => '60000',
                'address' => 'RESIDENCE PARC MONTCEAU BT B',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AIDAMCIE CFAIE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'VAL DE REUIL',
                'cp' => '27102',
                'address' => '41 RUE PAS DES HEURES ',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CENTRE DE FORMATION D APPRENTIS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AIX EN PROVENCE',
                'cp' => '13090',
                'address' => '7 RUE DU CHATEAU DE L HORLOGE',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CHAMBRE DE METIERS DE MEURTHE ET MOSELLE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LAXOU',
                'cp' => '54520',
                'address' => '4 RUE DE LA VOLOGNE',
                'cost' => '3000',
                'duration' => '9',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CHEMIN FAISANT NOTRE MAISON FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AROMAS',
                'cp' => '39240',
                'address' => 'NOTRE MAISON FORMATION',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ERGANES',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LE PLESSIS BELLEVILLE',
                'cp' => '60330',
                'address' => '5 AVENUE GEORGES BATAILLE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'FORMA2F',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ST YRIEIX LA PERCHE',
                'cp' => '87500',
                'address' => '22 AVENUE MICHEL GONDINET',
                'cost' => '3000',
                'duration' => '18',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA DE LA CREATION DU DESIGN ET DES METIERS D\'ART',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PARIS',
                'cp' => '75010',
                'address' => '21 RUE DE SAMBRE ET MEUSE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'INSTITUT DE FORMATION INTER PROFESSIONNEL DE L\'ALLIER',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AVERMES',
                'cp' => '30000',
                'address' => '11 ROUTE DE PARIS',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'INSTITUT MUNICIPAL D\'EDUCATION PERMANENTE DE PANTIN IMEPP',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PANTIN',
                'cp' => '93500',
                'address' => '10 RUE GAMBETTA',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ITP INSTITUT TECHNIQUE PRIVE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MARSEILLE',
                'cp' => '13007',
                'address' => '84 BD DE LA CORDERIE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'JMSA. FORMATION CONSEIL MALOT JEAN MICHEL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'CREIL',
                'cp' => '60100',
                'address' => '47-49 RUE JULES JUILLET',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'KURSUS FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'CESSON SEVIGNE',
                'cp' => '35510',
                'address' => '40 RUE DU BIGNON ',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'LEARNING PRO SASU',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BEAUCHAMPS',
                'cp' => '80770',
                'address' => '27 DOMAINE DU LAC',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'NACRE SARL  FORMEO',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PORTET SUR GARONNE',
                'cp' => '31120',
                'address' => '4 CHEMIN DES ROSSIGNOLS',
                'cost' => '3000',
                'duration' => '18',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'NCS FORMATION SARL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AUCH (32000)',
                'cp' => '32000',
                'address' => '31 Avenue de l\'Yser',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'NG FORMATIONS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ORANGE (84100)',
                'cp' => '84100',
                'address' => '289 avenue marÃ©chal foch ',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'PASSERELLES ET ACCOMPAGNEMENTS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LE ROBERT',
                'cp' => '97231',
                'address' => '21 RUE DES GOYAVIERS',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'PERFO SARL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'SAINT REMY SUR DUROLLE',
                'cp' => '63550',
                'address' => 'VOIRDIERES',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'RESEAU ACTION BUSINESS PARTNERS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BILLERE',
                'cp' => '64140',
                'address' => '85 AVENUE JEAN MERMOZ',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'SARL ABSOLU CONSULTING',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'TOULOUSE',
                'cp' => '31500',
                'address' => '3 AVENUE DU CIMETIERE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'SARL AFLOKKAT',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AJACCIO',
                'cp' => '20000',
                'address' => '7 COURS NAPOLEON',
                'cost' => '3000',
                'duration' => '4',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ACCUEIL PAYSAN AUVERGNE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BRIOUDE',
                'cp' => '43100',
                'address' => '53, RUE DE LA PARDIGE',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ADEPFO ASSOCIATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'TOULOUSE CEDEX 6',
                'cp' => '31080',
                'address' => '2 ESPL.COMPANS CAFFARELLI',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'A. G. A. P. FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'WAMBRECHIES (59118)',
                'cp' => '59118',
                'address' => '36 allée Boucher',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AIFCC INSERTION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'CAEN CEDEX 5',
                'cp' => '14077',
                'address' => '7 RUE PROFESSEUR J.ROUSSELOT',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AREFFIG - ADMINISTRATION RECHERCHE EXPERTISE ET FORMATION EN FINANCE INFORMATIQUE ET GESTION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Bordeaux',
                'cp' => '33000',
                'address' => '1 allée des lilas',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASSOCIATION INTERPRO.FORMATION CONTINUE DS LE CALVADOS(AIFCC)',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'villeneuve sur lot',
                'cp' => '47000',
                'address' => '20 rue des tubes',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASSOCIATION REGIONALE D\'EDUCATION PERMANENTE ILLE ARMOR',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'RENNES',
                'cp' => '35706',
                'address' => '190 AVENUE GENERAL GEORGE PATTON',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CENTRE DE FORMATION PROFESSIONNELLE ET DE PROMOTION AGRICOLE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'VIRE NORMANDIE',
                'cp' => '14500',
                'address' => 'ROUTE DE CAEN',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'cfa chambre des metiers',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ORLEANS',
                'cp' => '45000',
                'address' => '09 RUE DU 11 NOVEMBRE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CHAMBRE DE COMMERCE ET D\'INDUSTRIE ROCHEFORT (CCIR)',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ROCHEFORT',
                'cp' => '17306',
                'address' => 'CORDERIE ROYALE',
                'cost' => '3000',
                'duration' => '18',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'DEVELOPPEMENT AGRO ECONOMIQUE ET DE SECURITE ALIMENTAIRE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PASSAMAINTY',
                'cp' => '97605',
                'address' => '8 RESIDENCE RIVIERA',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ECOLE NORMALE SUPERIEURE DE LYON - ENS LYON',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LYON',
                'cp' => '69342',
                'address' => '15 PARVIS RENE DESCARTES',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'EURL CLARA MIOTTO -LA SOLUTION FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MONTPELLIER',
                'cp' => '34000 ',
                'address' => '1025 RUE HENRI BECQUEREL',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'FORMA2F',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ST YRIEIX LA PERCHE',
                'cp' => '87500',
                'address' => '22 AVENUE MICHEL GONDINET',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'FORMASUD EURL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PRAYSSAC',
                'cp' => '46220',
                'address' => '29 QUATER AVENUE DU COLONEL PARDES',
                'cost' => '3000',
                'duration' => '15',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'G I P  FORMATION CONTINUE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'REIMS CEDEX',
                'cp' => '51722',
                'address' => '17 BOULEVARD DE LA PAIX - CS 50033',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ISAAC DE L\'ETOILE - OGEC POITIERS NORD',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'POITIERS CEDEX',
                'cp' => '86001',
                'address' => '62 RUE DU PORTEAU',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'L\'ASSOSPHERE FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'CABESTANY',
                'cp' => '66330',
                'address' => '11 AVENUE AMPERE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'LINORA FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'CHAVIGNY',
                'cp' => '54230',
                'address' => '1 RUE DES ECOLES ',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'MARIE-ANGE ALEXANDRE CONSEIL - MAA CONSEIL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'COULANGES-LES-NEVERS',
                'cp' => '58660',
                'address' => '8 RUE DES FILLES',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'PASSERELLES ET ACCOMPAGNEMENTS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LE ROBERT',
                'cp' => '97231',
                'address' => '21 RUE DES GOYAVIERS',
                'cost' => '3000',
                'duration' => '364',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'POL\'ETAMINE FORMATIONS ET ECHANGES',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ALTKIRCH',
                'cp' => '68130',
                'address' => 'AVENUE DU 8E REGIMENT DE HUSSARDS  BAT. 23',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'SAS ECOFAC',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LE MANS',
                'cp' => '72000',
                'address' => '46 AVENUE FRANCOIS MITERRAND',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'STE COOPERATIVE ARIAC',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'CLERMONT L HERAULT (34800)',
                'cp' => '34800',
                'address' => '8 AVENUE DU LAC',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'T L C',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AMIENS',
                'cp' => '80000',
                'address' => '26 BOULEVARD DES FEDERES',
                'cost' => '3000',
                'duration' => '8',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'UNIVERSITE DE LIMOGES',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LIMOGES',
                'cp' => '87000',
                'address' => '209 BOULEVARD DE VANTEAUX',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'UNIVERSITE JEAN MONNET (UJM)',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ST ETIENNE',
                'cp' => '42023',
                'address' => '21 RUE DENIS PAPIN',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'WOLTERS  KLUWER FRANCE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PARIS 17',
                'cp' => '75814',
                'address' => '14, RUE FRUCTIDOR',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AGIR POUR LA MOBILISATION DES SAVOIRS AMS GRAND SUD',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'TOULOUSE',
                'cp' => '31000',
                'address' => '70 BD MATABIAU',
                'cost' => '3000',
                'duration' => '4',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ANTEE FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'JOUE LES TOURS',
                'cp' => '37300',
                'address' => '40 rue des martyrs',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASSOCIATION DE GESTION DU CONSERVATOIRE NATIONAL DES ARTS ET METIERS DE LA REUNION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LE PORT',
                'cp' => '97827',
                'address' => '18 RUE CLAUDE CHAPPE ZAC 2000 ',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AXYS S.A.R.L.',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LA ROCHELLE',
                'cp' => '17000',
                'address' => '33 RUE DU REMPART ST CLAUDE',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CONSERVATOIRE NATIONAL DES ARTS ET METIERS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PARIS 03',
                'cp' => '75141',
                'address' => '292 RUE ST MARTIN',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ESCENDO FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'TOURS',
                'cp' => '37000',
                'address' => '01 RUE LEO DELIBES -',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => ' GIP FCIP EDUCATION ET FORMATION TOUT AU LONG DE LA VIE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'POITIERS',
                'cp' => '86000',
                'address' => '12 rue des arts',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA ARVE FAUCIGNY',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BONNEVILLE',
                'cp' => '74134',
                'address' => '210 QUAI DU PARQUET',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA DE CORSE DU SUD   LYCEE LAETITIA BONAPARTE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AJACCIO',
                'cp' => '20184',
                'address' => 'AV NAPOLEON III',
                'cost' => '3000',
                'duration' => '10',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA DU RHONE - LYCEE LOUIS ARMAND',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'VILLEFRANCHE SUR SAONE',
                'cp' => '69651',
                'address' => '507 AVENUE DU BEAUJOLAIS',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'INSTITUT UNIVERSITAIRE DE TECHNOLOGIE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LIMOGES CEDEX',
                'cp' => '87065',
                'address' => 'ALLEE ANDRE MAUROIS',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ADALIANCE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BOULOGNE BILLANCOURT',
                'cp' => '92100',
                'address' => '83 BOULEVARD DE LA REPUBLIQUE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AFEPT   ASSOC. FORMATION ET EDUCATION PERMANENTE DE TIVOLI',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BORDEAUX',
                'cp' => '33000',
                'address' => '40 RUE DE MARSEILLE',
                'cost' => '3000',
                'duration' => '10',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AFTEC',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ORLEANS',
                'cp' => '45058',
                'address' => '22 AVENUE DES DROITS DE L\'HOMME',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ALPHA FORMATION O.I ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'SAINTE CLOTILDE',
                'cp' => '97490',
                'address' => '14, RUE JULES HERMANN',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ARCOOP Scop Sarl',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ROMANS SUR ISERE',
                'cp' => '26106',
                'address' => '2 rue Camille Claudel',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASS DES AMIS DE L\'ENSEIG TECH D\'ARGENTEUIL ET DES ENVIRONS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ARGENTEUIL',
                'cp' => '95104',
                'address' => '84 B BD HELOISE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASSOC GESTION DE LA FORMATION CONTINUE, PROFES   SUPERIEURE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Bordeaux',
                'cp' => '33000',
                'address' => '25 rue des buffles',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASS REG DU CONSERVATOIRE NAT. DES ARTS ET METIERS DE PIC',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AMIENS',
                'cp' => '80025',
                'address' => 'AVENUE DES FACULTES',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ATRYA',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'GUNDERSHOFFEN',
                'cp' => '67110',
                'address' => 'ZI LE MOULIN',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AVENIR & TALENT',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'TOURS',
                'cp' => '37000',
                'address' => '8 rue Alexander Fleming',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'BP FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MONTAUT',
                'cp' => '64800',
                'address' => 'ROUTE DE LOURDES',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CAP SERVICES',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LYON 03',
                'cp' => '69003',
                'address' => '11 RUE DUPHOT',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CCI  FORMATION COTE D\'OR ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'DIJON',
                'cp' => '2100',
                'address' => 'PLACE JEAN BOUHEY',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CHLOROPHYLLE INFORMATIQUE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BREST',
                'cp' => '29200',
                'address' => '21 RUE DU 8 MAI 1945',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'XXL Formation',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MONT ST AIGNAN (76824)',
                'cp' => '76824',
                'address' => '34 RUE RAYMOND ARON BP 520',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'A2COM FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PACE',
                'cp' => '35740',
                'address' => '1 BOULEVARD DU TRIEUX',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ACCRE SAS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ROMAGNAT',
                'cp' => '63540',
                'address' => '20, RUE ENRICO FERMI',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'A SENATUS CONSULTO',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PARIS 14',
                'cp' => '75014',
                'address' => '23 RUE BOYER - BARRET',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'B AND B PERFORMANCE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'FONTENAY SOUS BOIS',
                'cp' => '94120',
                'address' => '57 BOULEVARD DE VERDUN',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CHAMBRE DE METIERS ET DE L\'ARTISANAT DE LA DROME',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Bordeaux',
                'cp' => '33000',
                'address' => 'rue du dome',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'EDINOVO FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Bordeaux',
                'cp' => '33000',
                'address' => 'place de la bourse',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',

                ],
                [
                'classes_name' => 'IMAGE SCOP',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'NIMES',
                'cp' => '30900',
                'address' => '125 RUE DE L\'HOSTELLERIE ',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'MME LAVANDIER MARJOLAINE - EIRL LES CLES DE LA GESTION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'TOURNEFEUILLE',
                'cp' => '31170',
                'address' => '13 RUE DE MONTAIGU',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'QUINTESSENCE FORMATION SARL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Marseille',
                'cp' => '13567',
                'address' => '10 PLACE DE LA JOLIETTE',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AFPI 8002',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'SAINT QUENTIN',
                'cp' => '21000',
                'address' => '114 CHAUSSEE ROMAINE',
                'cost' => '3000',
                'duration' => '4',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ALPHA FORMA',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LE BLANC MESNIL',
                'cp' => '93150',
                'address' => '42 AVENUE MATHILDE EMILIE',
                'cost' => '3000',
                'duration' => '30',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASFORQUAL BTP ASSOCIATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'FOIX CEDEX',
                'cp' => '90010',
                'address' => '14 AVENUE DE L\'ARIEGE BP 1',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASMFP 77',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AVON',
                'cp' => '77210',
                'address' => '38 AVENUE FRANKLIN ROOSEVELT',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASSOCIATION INTERPROFESSIONNELLE POUR LA FORMATION PERMANENTE DANS LE SARLADAIS / AIFS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Bordeaux',
                'cp' => '33000',
                'address' => '26 rue des faussets',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ATFI  WAIBSPE3D',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MASSY',
                'cp' => '91300',
                'address' => '24 RESIDENCE DU PARC',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AT FORMATIONS ET CONSEILS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'REIMS',
                'cp' => '51100',
                'address' => '4 PLACE ARISTIDE BRIAND',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AZUR FORMATIONS ZI BRAYE DFE CAU',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LA PENNE SUR HUVEAUNE',
                'cp' => '13821',
                'address' => '371 AVENUE DE LA  RASCLAVE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CB BREIZH',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ST GREGOIRE',
                'cp' => '35760',
                'address' => 'ESPACE PERFORMANCE ALPHASIS',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ARCADE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AIX EN PROVENCE CEDEX 1',
                'cp' => '13617',
                'address' => '6 PLACE BARTHELEMY NIOLLON',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'DJEM',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PONTOISE',
                'cp' => '95300',
                'address' => '16 RUE AMPÃ¨RE',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ELLIPSE FORMATION ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PARIS',
                'cp' => '75011',
                'address' => '8, CITÃ© JOLY',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA DU VELAY LYCEE CHARLES ET ADRIEN DUPUY',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LE PUY EN VELAY CEDEX',
                'cp' => '43009',
                'address' => '2/4 AVENUE DU DOCTEUR DURAND',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'INST NATIONAL DE L\'AUDIOVISUEL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BRY SUR MARNE',
                'cp' => '94360',
                'address' => '4 AVE DE L\'EUROPE',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CENTRE DE GESTION DE CHAMPAGNE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Bordeaux',
                'cp' => '33000',
                'address' => '12 rue des faussets',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CONSULTING 26',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Auch',
                'cp' => '32000',
                'address' => '14 place des morts-vivants',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA VIVARAIS PROVENCE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Paris',
                'cp' => '75000',
                'address' => '89 avenue de la soie',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'PREPAVENIR FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Paris',
                'cp' => '75010',
                'address' => '46 place de la république',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'LAMED SERVICES',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Bordeaux',
                'cp' => '33000',
                'address' => '1 rue du mur',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ACTELIOR CONSEIL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'CHAMPAGNE AU MONT D OR',
                'cp' => '69410',
                'address' => '7BIS RUE DES AULNES',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AGCNAM DE BRETAGNE (ASSOCIATION DE GESTION DU CNAM EN BRETAGNE)CONSERVATOIRE ARTS ET METIERS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Bordeaux',
                'cp' => '33000',
                'address' => '12 rue des ames',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASSOCIATION  DE GESTION DU CNAM EN REGION CENTRE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ORLEANS',
                'cp' => '45000',
                'address' => '21 BIS RUE EUGENE VIGNAT',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASSOCIATION UDEL ENTREPRISE ET FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ORLEANS CEDEX 1',
                'cp' => '45058',
                'address' => '14 BLD ROCHEPLATTE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASS REG DU CONSERVATOIRE NAT. DES ARTS ET METIERS DE PIC',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AMIENS',
                'cp' => '80025',
                'address' => 'AVENUE DES FACULTES',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASS. REGIONALE DE FORMATION POUR L ARTISANAT DU BATIMENT',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'POITIERS',
                'cp' => '86000',
                'address' => '14 RUE DES FRERES LUMIERE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ATHENA TRAINING SARL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ST ANDRE',
                'cp' => '97440',
                'address' => '4 BIS RUE GABRIEL VAYABOURY',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ATOVA CONSEIL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'VILLEURBANNE',
                'cp' => '69100',
                'address' => '54 RUE PAULE VERLAINE',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CAMPUS VEOLIA ENVIRONNEMENT IDF',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MEYZIEU',
                'cp' => '69881',
                'address' => '25 AVENUE LIONEL TERRAY',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CCI  FORMATION COTE D\'OR ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'DIJON',
                'cp' => '21000',
                'address' => 'PLACE JEAN BOUHEY',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CFPPA  CENTRE DE FORMATION PRO ET DE PROMO AGRICOLE DE NYONS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'NYONS',
                'cp' => '26110',
                'address' => '2 AVENUE DE VENTEROL',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AFTEC',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'ORLEANS',
                'cp' => '45058',
                'address' => '22 AVENUE DES DROITS DE L\'HOMME',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AGISS ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LYON 03',
                'cp' => '69003',
                'address' => '71 COURS ALBERT THOMAS',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASSOCIATION DE GESTION DU CONSERVATOIRE NATIONAL DES ARTS ET MÃ‰TIERS DE LA REUNION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LE PORT',
                'cp' => '97827',
                'address' => '18 RUE CLAUDE CHAPPE ZAC 2000 ',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CCI  DE TOULOUSE ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'TOULOUSE',
                'cp' => '31002',
                'address' => '2 RUE D\'ALSACE LORRAINE',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CENTRE D\'AIDE DE DIALOGUE ET D\'ECOUTE - CADE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'STE LUCE',
                'cp' => '97228',
                'address' => 'PLACE DES COCOTIERS',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CHAMBRE DE COMMERCE ET D\'INDUSTRIE DE LIMOGES ET DE LA HAUTE-VIENNE - CCI FORMATION - CAMPUS CONSULAIRE ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LIMOGES ',
                'cp' => '87011',
                'address' => '16 PLACE JOURDAN',
                'cost' => '3000',
                'duration' => '18',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ECOLE D\'ELECTRICITE DE PRODUCTION ET DES METHODES INDUSTRIELLES',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'CERGY',
                'cp' => '95092',
                'address' => '13 BOULEVARD DE L\'HAUTIL',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'EURL CLARA MIOTTO -LA SOLUTION FORMATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MONTPELLIER',
                'cp' => '34000 ',
                'address' => '1025 RUE HENRI BECQUEREL',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'FEDE ASSOCIATIVE  POUR DEVEL DE L EMPLOI AGRICOLE ET RURAL',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BAGNOLET',
                'cp' => '93170',
                'address' => '104 RUE ROBESPIERRE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA DU VAR',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LA SEYNE SUR MER',
                'cp' => '83514',
                'address' => 'LYCEE LANGEVIN BD L\'EUROPE',
                'cost' => '3000',
                'duration' => '18',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AFPI 8002',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'SAINT QUENTIN',
                'cp' => '21000',
                'address' => '114 CHAUSSEE ROMAINE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'C.C.I.M. (CHAMBRE DE COMMERCE ET D\'INDUSTRIE DU MORBIHAN)',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LORIENT (56323)',
                'cp' => '56323',
                'address' => '2 BIS RUE EDOUARD BEAUVAIS',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'AFPIA EST NORD',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LIFFOL LE GRAND',
                'cp' => '88350',
                'address' => '2 RUE DU 8 MAI 1945  BP 25',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASFIS',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PARIS',
                'cp' => '75001',
                'address' => '44 RUE DU LOUVRE',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'ASS REG DU CONSERVATOIRE NAT. DES ARTS ET METIERS DE PIC',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AMIENS',
                'cp' => '80025',
                'address' => 'AVENUE DES FACULTES',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'BTP CFA MIDI-PYRENEES ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'TOULOUSE CEDEX 1',
                'cp' => '31035',
                'address' => '3 IMPASSE GEORGES DAZET',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CFA DU BATIMENT',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MONTIGNY LES METZ',
                'cp' => '57950',
                'address' => '154 CHEMIN DE BLORY',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CFC AGEPAC - Apprentis d\'Auteuil Mayotte',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MAMOUDZO',
                'cp' => '97600',
                'address' => 'BP 1023',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA DE BESANCON',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BESANCON',
                'cp' => '25000',
                'address' => '35 AVENUE DE MONTRAPON',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA DE CORSE DU SUD   LYCEE LAETITIA BONAPARTE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'AJACCIO',
                'cp' => '20184',
                'address' => 'AV NAPOLEON III',
                'cost' => '3000',
                'duration' => '24',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA LYON METROPOLE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'LYON CEDEX 08',
                'cp' => '69372',
                'address' => '41 RUE ANTOINE LUMIERE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA MARSEILLE MEDITERRANEE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MARSEILLE 10',
                'cp' => '13010',
                'address' => 'LYCEE JEAN PERRIN',
                'cost' => '3000',
                'duration' => '36',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA NORD ISERE - LYCEE ELLA FITZGERALD ',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'BOURGOIN JALLIEU (38300)',
                'cp' => '38300',
                'address' => '33 AVENUE D\'ITALIE',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'CHAMBRE DE COMMERCE ET D\'INDUSTRIE DE REGION I PARIS IDF',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'Paris',
                'cp' => '75000',
                'address' => 'place principale',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'GRETA MARSEILLE MEDITERRANEE',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MARSEILLE 10',
                'cp' => '13010',
                'address' => 'LYCEE JEAN PERRIN',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'IN\'FOR (INGENIERIE FORMATION)',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'MAZAMET',
                'cp' => '81200',
                'address' => '23 RUE DE LA VANNE',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
                ],
                [
                'classes_name' => 'INSTITUT METIERS DE L\'ART ET ARTISANAT ASSOCIATION',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'REVEL (31250)',
                'cp' => '31250',
                'address' => '20 RUE JEAN MOULIN',
                'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
              
                ],
                [
                'classes_name' => 'ESMA',
                'contact' => 'mr truc',
                'mail' => 'mail@mail.com',
                'tel' => '0512345678',
                'city' => 'PARIS',
                'cp' => '75000',
                'address' => 'AVENUE DU DOCTEUR DURAND',
                'cost' => '3000',
                'duration' => '6',
                'link' => 'http://www.wf3.fr/',
              
                ],            
             [
                 'classes_name' => 'REGIMENT DU SERVICE MILITAIRE ADAPTE DE LA GUYANE',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'GUYANE',
                 'cp' => '43009',
                 'address' => '2/4 AVENUE DU DOCTEUR DURAND',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'CHAMBRE DE COMMERCE D\'INDUSTRIE D\'AJACCIO SARTENE
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'AJACCIO
',
                 'cp' => '20000
',
                 'address' => 'QUAI L\'HERMINIER
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'EVEIL ET SCIENCES
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'VENCE
',
                 'cp' => '61400
',
                 'address' => '7 AVENUE DES POILUS
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'CENTRE DE FORMATION PROFESSIONNELLE ET DE PROMOTION AGRICOLE
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'COCONI
',
                 'cp' => '97670
',
                 'address' => '2 rue de paradis',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'CFPPA VESOUL
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'VESOUL
',
                 'cp' => '70014
',
                 'address' => '16 RUE EDOUARD BELIN - CS 60363
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'GRETA LYON METROPOLE
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'LYON CEDEX 08
',
                 'cp' => '69372
',
                 'address' => '41 RUE ANTOINE LUMIERE
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'CNAM PACA
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'MARSEILLE 15
',
                 'cp' => '13015
',
                 'address' => '12 PLACE DES ABATTOIRS
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'VET AGRO SUP (INST ENSEIGN SUP,RECH ALIM...)
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'MARCY L ETOILE
',
                 'cp' => '69280
',
                 'address' => '1 AVENUE BOURGELAT
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'FORMASUP PARIS
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'PARIS 06
',
                 'cp' => '75006
',
                 'address' => '4 RUE BLAISE DESGOFFE
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'GRETA LYON METROPOLE
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'LYON CEDEX 08
',
                 'cp' => '69372
',
                 'address' => '41 RUE ANTOINE LUMIERE
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'A D C I
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'ROMAIN
',
                 'cp' => '51140
',
                 'address' => '25 ROUTE DE VENTELAY
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'CHAMBRE D\'AGRICULTURE LA MAYENNE
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'LAVAL
',
                 'cp' => '53061
',
                 'address' => 'RUE ALBERT EINSTEIN - CHANGE
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'CHAMBRE REG. METIERS BRETAGNE SERVICE REG. EMPLOI FORMATION
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'BREST',
                 'cp' => '53000',
                 'address' => 'place des marins',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'GRETA DE GRENOBLE
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'GRENOBLE CEDEX 2
',
                 'cp' => '38030
',
                 'address' => 'LYCEE TECHNIQUE VAUCANSON
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'GRETA DU LIVRADOIS FOREZ
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'PAU',
                 'cp' => '64000',
                 'address' => '20 rue des faussets',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'LYCEE YVES THEPOT
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'AUCH',
                 'cp' => '32000',
                 'address' => '24 place des armoiries',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'ASSOCIATION DU DOMAINE DU RAYOL
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'RAYOL-CANADEL
',
                 'cp' => '83820
',
                 'address' => 'Avenue du Commandant Rigaud
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'LYCEE PROFESSIONNEL PRIVE CLAIR FOYER ASSOCIATION
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'Bordeaux',
                 'cp' => '33000',
                 'address' => '45 rue des arts',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'LYCEE PROFESSIONNEL PRIVE NAZARETH
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'Nazille',
                 'cp' => '45200',
                 'address' => '12 place du foyer',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'LYCEE TECHNIQUE PRIVE MONTPLAISIR
',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'VALENCE
',
                 'cp' => '26000
',
                 'address' => '75 RUE MONTPLAISIR
',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'UNIVERSITE DE CAEN NORMANDIE / SERVICE UNIVERSITAIRE  FORMATION CONTINUE ET APPRENTISSAGE - SUFCA

',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'CAEN
',
                 'cp' => '14000
',
                 'address' => 'ESPLANADE DE LA PAIX

',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],
             [
                 'classes_name' => 'ENM Bordeaux

',
                 'contact' => 'mr truc',
                 'mail' => 'mail@mail.com',
                 'tel' => '0512345678',
                 'city' => 'BORDEAUX
',
                 'cp' => '33000
',
                 'address' => 'rue du hâ

',
                 'cost' => '3000',
                'duration' => '12',
                'link' => 'http://www.wf3.fr/',
             ],

         ];

        Classe::insert($data);
    }
}
